from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.action_chains import ActionChains


driver=webdriver.Edge()
driver.maximize_window()
url="https://www.saucedemo.com/"
driver.get(url)
driver.implicitly_wait(15)

username=driver.find_element(By.NAME,"user-name")
password=driver.find_element(By.NAME,"password")
username.send_keys("standard_user")
# time.sleep(1)
password.send_keys("secret_sauce")
# time.sleep(1)
loginButton=driver.find_element(By.NAME,"login-button")
loginButton.click()
time.sleep(1)
options=driver.find_element(By.XPATH,'//*[@id="header_container"]/div[2]/div/span/select')
select=Select(options)
select.select_by_value("lohi")
time.sleep(1)

driver.execute_script("window.scrollBy(0,500)")
time.sleep(1)
driver.execute_script("window.scrollTo(0,0)")
time.sleep(1)
addToCart1 = WebDriverWait(driver, 10).until(
    EC.element_to_be_clickable((By.ID, "add-to-cart-sauce-labs-backpack"))
)
addToCart2=WebDriverWait(driver,10).until(EC.element_to_be_clickable((By.ID,"add-to-cart-test.allthethings()-t-shirt-(red)")))

addToCart1.click()
time.sleep(1)
addToCart2.click()
time.sleep(1)
# driver.execute_script("window.open('https://www.saucedemo.com/inventory-item.html?id=4')")
# driver.switch_to.window(driver.window_handles[-1])
# driver.switch_to.window(driver.window_handles[0])
productDetails=driver.find_element(By.CSS_SELECTOR,"#item_4_title_link > div")
productDetails.click()
time.sleep(2)
backToProductPage=driver.find_element(By.ID,"back-to-products")
backToProductPage.click()
time.sleep(2)
cartPage=driver.find_element(By.XPATH,'//*[@id="shopping_cart_container"]/a')
cartPage.click()
time.sleep(3)
remove_btn=driver.find_element(By.ID,"remove-sauce-labs-backpack")
remove_btn.click()
time.sleep(2)
checkout_btn=driver.find_element(By.NAME,"checkout")
checkout_btn.click()
time.sleep(2)
checkout_fname=driver.find_element(By.ID,"first-name")
checkout_fname.send_keys("John")
time.sleep(1)
checkout_lname=driver.find_element(By.ID,"last-name")
checkout_lname.send_keys("Smith")
time.sleep(1)
zip_code=driver.find_element(By.ID,"postal-code")
zip_code.send_keys("44600")
time.sleep(1)
continue_btn=driver.find_element(By.ID,"continue")
continue_btn.click()
time.sleep(2)
driver.execute_script("window.scrollBy(0,500)")
time.sleep(1)
# cancel_btn=driver.find_element(By.NAME,"cancel")
# cancel_btn.click()
# time.sleep(2)
finish_btn=driver.find_element(By.NAME,"finish")
finish_btn.click()
time.sleep(3)
backToHome=driver.find_element(By.NAME,"back-to-products")
backToHome.click()
time.sleep(2)
driver.quit()